# Generated by Django 2.2.14 on 2022-05-09 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190630_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Sb', 'Shortboard'), ('Lb', 'Longboard'), ('F', 'Fish'), ('Pb', 'Paddleboard')], max_length=2),
        ),
    ]
